export enum MutationTypes {
  SET_CAMPAIGNS_LIST = 'SET_CAMPAIGNS_LIST',
  SET_CAMPAIGN_BANNER = 'SET_CAMPAIGN_BANNER',
  DELETE_CAMPAIGN = 'DELETE_CAMPAIGN',
  SET_CAMPAIGN_INVITATIONS = 'SET_CAMPAIGN_INVITATIONS'
}

export enum ActionTypes {
  FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS',
  FETCH_INVITATIONS = 'FETCH_INVITATIONS',
  DELETE_CAMPAIGN = 'DELETE_CAMPAIGN',
  GET_CAMPAIGN_DETAILS = 'GET_CAMPAIGN_DETAILS'
}