export enum MutationTypes {
  SET_CAMPAIGNS_LIST = 'SET_CAMPAIGNS_LIST',
  SET_CAMPAIGN_BANNER = 'SET_CAMPAIGN_BANNER',
  DELETE_CAMPAIGN = 'DELETE_CAMPAIGN',
  SET_CAMPAIGN_INVITATIONS = 'SET_CAMPAIGN_INVITATIONS',
  SELECT_MAP = 'SELECT_MAP',
  UNSELECT_ALL_TOKENS = 'UNSELECT_ALL_TOKENS',
  SELECT_TOKEN = 'SELECT_TOKEN',
  MOVE_TOKEN = 'MOVE_TOKEN'
}

export enum ActionTypes {
  FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS',
  FETCH_INVITATIONS = 'FETCH_INVITATIONS',
  DELETE_CAMPAIGN = 'DELETE_CAMPAIGN',
  GET_CAMPAIGN_DETAILS = 'GET_CAMPAIGN_DETAILS',
}